# ==============================================================================
# AbaCompGen — Advanced Publication-Ready Analysis
# A. baumannii Comparative Genomics | 23 Figures + Full Statistics
#
# Replication + Extension of:
#   Kumkar et al. 2022 — Front. Cell. Infect. Microbiol. 12:997897
#   doi: 10.3389/fcimb.2022.997897
#
# HOW TO SET PATHS — three options (in order of priority):
#
#   Option 1 (recommended): Set environment variables before running:
#     export RESULTS_DIR=/path/to/your/project/results
#     export PROJECT_DIR=/path/to/your/project
#     conda run -n r_env Rscript advanced_analysis.R
#
#   Option 2: Pass as command-line arguments:
#     Rscript advanced_analysis.R /path/to/project /path/to/project/results
#
#   Option 3: Edit the fallback defaults in Section 1 below.
#
# REQUIRED INPUT FILES (all generated by the pipeline steps 00–11):
#   $RESULTS_DIR/13_summary_tables/metadata.tsv          ← or $PROJECT_DIR/metadata.tsv
#   $RESULTS_DIR/13_summary_tables/mlst_combined.tsv
#   $RESULTS_DIR/13_summary_tables/ARG_counts.tsv
#   $RESULTS_DIR/13_summary_tables/annotation_summary.tsv
#   $RESULTS_DIR/13_summary_tables/plasmid_summary.tsv
#   $RESULTS_DIR/13_summary_tables/prophage_summary.tsv
#   $RESULTS_DIR/13_summary_tables/VFG_counts.tsv
#   $RESULTS_DIR/13_summary_tables/amr_matrix.csv
#   $RESULTS_DIR/13_summary_tables/IS_family_frequency.tsv
#   $RESULTS_DIR/13_summary_tables/IS_ARG_linkage.tsv
#   $RESULTS_DIR/13_summary_tables/mob_suite_summary.tsv
#   $RESULTS_DIR/13_summary_tables/prophage_ARG_check.tsv
#   $RESULTS_DIR/09_SNP_phylogeny/iqtree/acinetobacter_snp.treefile
#
# OUTPUT:
#   $RESULTS_DIR/ADVANCED_FIGURES/  ← 23 figures (PDF + PNG) + statistics text
# ==============================================================================

# ── 0. PACKAGES ────────────────────────────────────────────────────────────────
pkgs <- c(
  "tidyverse", "ggpubr", "pheatmap", "viridis", "corrplot",
  "ggrepel", "ggtreeExtra", "ggtree", "rstatix", "scales", "patchwork",
  "ggridges", "RColorBrewer", "vegan", "ggalluvial", "treemapify",
  "ggbeeswarm", "lme4", "broom", "effectsize", "ape", "phytools"
)
new_pkgs <- pkgs[!pkgs %in% rownames(installed.packages())]
if (length(new_pkgs)) {
  message("Installing missing packages: ", paste(new_pkgs, collapse=", "))
  install.packages(new_pkgs, repos = "https://cloud.r-project.org", quiet = TRUE)
}
suppressPackageStartupMessages(lapply(pkgs, library, character.only = TRUE))
cat("Packages loaded\n")

# ── 1. PATHS ───────────────────────────────────────────────────────────────────
# Priority: CLI args > environment variables > defaults

args <- commandArgs(trailingOnly = TRUE)

if (length(args) >= 2) {
  PROJECT_DIR <- args[1]
  RESULTS_DIR <- args[2]
} else if (length(args) == 1) {
  PROJECT_DIR <- args[1]
  RESULTS_DIR <- file.path(PROJECT_DIR, "results")
} else {
  # Fall back to environment variables, then sensible defaults
  PROJECT_DIR <- Sys.getenv("PROJECT_DIR",
                  unset = file.path(Sys.getenv("HOME"), "acinetobacter_genomics"))
  RESULTS_DIR <- Sys.getenv("RESULTS_DIR",
                  unset = file.path(PROJECT_DIR, "results"))
}

SUM_DIR <- file.path(RESULTS_DIR, "13_summary_tables")
FIG_DIR <- file.path(RESULTS_DIR, "ADVANCED_FIGURES")

dir.create(FIG_DIR, showWarnings = FALSE, recursive = TRUE)

cat(sprintf(
  "\n── Path Configuration ──────────────────────────\n  Project : %s\n  Results : %s\n  Summary : %s\n  Figures : %s\n────────────────────────────────────────────────\n\n",
  PROJECT_DIR, RESULTS_DIR, SUM_DIR, FIG_DIR
))

# ── 1b. SAFE FILE LOADER ──────────────────────────────────────────────────────
# Loads a table with a warning instead of crashing if the file is missing.
safe_load <- function(path, reader = read_tsv, ...) {
  if (!file.exists(path)) {
    warning(sprintf("[SKIP] File not found: %s", path), call. = FALSE)
    return(NULL)
  }
  tryCatch(
    reader(path, show_col_types = FALSE, ...),
    error = function(e) {
      warning(sprintf("[ERROR] Could not read %s: %s", path, e$message), call. = FALSE)
      NULL
    }
  )
}

# ── 2. PUBLICATION THEME ───────────────────────────────────────────────────────
theme_pub <- function(base_size = 12) {
  theme_classic(base_size = base_size) +
    theme(
      axis.line         = element_line(colour = "black", linewidth = 0.5),
      axis.ticks        = element_line(colour = "black", linewidth = 0.4),
      axis.text         = element_text(colour = "black", size = base_size - 1),
      axis.title        = element_text(colour = "black", size = base_size, face = "bold"),
      panel.grid        = element_blank(),
      panel.background  = element_blank(),
      plot.background   = element_blank(),
      legend.background = element_blank(),
      legend.key        = element_blank(),
      legend.title      = element_text(size = base_size - 1, face = "bold"),
      legend.text       = element_text(size = base_size - 2),
      plot.title        = element_text(size = base_size + 2, face = "bold",
                                       hjust = 0, margin = margin(b = 4)),
      plot.subtitle     = element_text(size = base_size - 1, colour = "grey40",
                                       hjust = 0, margin = margin(b = 8)),
      plot.caption      = element_text(size = base_size - 3, colour = "grey55", hjust = 1),
      strip.background  = element_rect(fill = "grey93", colour = NA),
      strip.text        = element_text(size = base_size - 1, face = "bold"),
      plot.margin       = margin(10, 14, 8, 10)
    )
}

# ── Colour palettes ────────────────────────────────────────────────────────────
PAL_ST <- c(
  "ST2"   = "#E63946", "ST622" = "#457B9D", "ST10"  = "#2A9D8F",
  "ST25"  = "#E9C46A", "ST1"   = "#F4A261", "ST85"  = "#9D4EDD",
  "Other" = "#A8DADC", "Unknown" = "#CED4DA"
)
names(PAL_ST) <- trimws(names(PAL_ST))

HOSP_ORDER <- c("AIIMS","CMC","JNU","ICMR","SGRH","TMC","PGIMER","SRMC","MMC")
PAL_HOSP   <- setNames(
  c("#E63946","#457B9D","#2A9D8F","#E9C46A","#F4A261","#A8DADC","#6A4C93","#C77DFF","#CED4DA"),
  HOSP_ORDER
)

PAL_SPEC <- c("Blood"="#C1121F","Sputum"="#4A90D9","Wound"="#2A9D8F",
              "Urine"="#E9C46A","Pus"="#F4A261","NA"="#CED4DA")

PAL_LOC  <- c("New_Delhi"="#E63946","Tamil_Nadu"="#457B9D",
              "West_Bengal"="#2A9D8F","Chandigarh"="#E9C46A","Other"="#CED4DA")

# Returns a complete named colour vector even when values are not in the palette
safe_pal <- function(pal, vals) {
  vals    <- as.character(vals)
  present <- intersect(vals, names(pal))
  missing <- setdiff(vals, names(pal))
  extra   <- setNames(grey.colors(max(length(missing), 1L), start = 0.5), missing)
  c(pal[present], extra)[vals]
}

# ── Save helper ────────────────────────────────────────────────────────────────
save_fig <- function(p, name, w = 8, h = 6) {
  ggsave(file.path(FIG_DIR, paste0(name, ".pdf")), p,
         width = w, height = h, useDingbats = FALSE)
  ggsave(file.path(FIG_DIR, paste0(name, ".png")), p,
         width = w, height = h, dpi = 300)
  cat("   \u2714", name, "\n")
}

# ══════════════════════════════════════════════════════════════════════════════
# 3. LOAD ALL DATA
# ══════════════════════════════════════════════════════════════════════════════
cat("\n Loading data...\n")

# Metadata — check both the summary tables dir and the project root
meta_path <- file.path(SUM_DIR, "metadata.tsv")
if (!file.exists(meta_path)) meta_path <- file.path(PROJECT_DIR, "metadata.tsv")

meta <- safe_load(meta_path,
                  col_types = cols(sequence_type   = col_character(),
                                   collection_year = col_double()))
if (is.null(meta)) stop("metadata.tsv not found. Run step00_setup.sh first.")
meta <- rename(meta, year = collection_year)

# MLST
mlst_raw <- safe_load(file.path(SUM_DIR, "mlst_combined.tsv"))
if (!is.null(mlst_raw)) {
  st_col <- if ("ST_pasteur" %in% names(mlst_raw)) "ST_pasteur" else names(mlst_raw)[2]
  mlst_st <- mlst_raw %>%
    select(sample, ST_val = all_of(st_col)) %>%
    mutate(ST_val = as.character(ST_val)) %>%
    distinct(sample, .keep_all = TRUE)
  meta <- meta %>% full_join(mlst_st, by = "sample")
} else {
  meta$ST_val <- NA_character_
}

meta <- meta %>%
  mutate(
    year     = suppressWarnings(as.numeric(as.character(year))),
    year     = replace_na(year, 0),
    era      = case_when(year == 0     ~ "Unknown",
                         year <= 2010  ~ "Early (\u22642010)",
                         year <= 2017  ~ "Mid (2011-2017)",
                         TRUE          ~ "Recent (2018-2020)"),
    hospital = replace_na(as.character(hospital), "Unknown"),
    location = replace_na(as.character(location), "Unknown"),
    specimen = replace_na(as.character(specimen), "Unknown"),
    ST_Group = case_when(
      str_detect(as.character(ST_val), "^(ST)?2$")   ~ "ST2",
      str_detect(as.character(ST_val), "^(ST)?622$") ~ "ST622",
      str_detect(as.character(ST_val), "^(ST)?10$")  ~ "ST10",
      str_detect(as.character(ST_val), "^(ST)?25$")  ~ "ST25",
      str_detect(as.character(ST_val), "^(ST)?1$")   ~ "ST1",
      str_detect(as.character(ST_val), "^(ST)?85$")  ~ "ST85",
      is.na(ST_val) | ST_val %in% c("NA","?","-","ND","novel") ~ "Unknown",
      TRUE ~ "Other"
    )
  )

cat("ST_Group distribution:\n"); print(table(meta$ST_Group, useNA = "always"))

# Core tables
arg_count    <- safe_load(file.path(SUM_DIR, "ARG_counts.tsv"))
annot        <- safe_load(file.path(SUM_DIR, "annotation_summary.tsv"))
plasmid      <- safe_load(file.path(SUM_DIR, "plasmid_summary.tsv"))
prophage_sum <- safe_load(file.path(SUM_DIR, "prophage_summary.tsv"))
vfg_count    <- safe_load(file.path(SUM_DIR, "VFG_counts.tsv"))
amr_mat      <- safe_load(file.path(SUM_DIR, "amr_matrix.csv"), reader = read_csv)

# Tables that were missing from the original script — loaded here
is_freq      <- safe_load(file.path(SUM_DIR, "IS_family_frequency.tsv"))
is_arg_link  <- safe_load(file.path(SUM_DIR, "IS_ARG_linkage.tsv"))
mob_suite    <- safe_load(file.path(SUM_DIR, "mob_suite_summary.tsv"))
prophage_arg <- safe_load(file.path(SUM_DIR, "prophage_ARG_check.tsv"))

# OXA-23 presence from AMR matrix
if (!is.null(amr_mat) && "OXA-23" %in% names(amr_mat)) {
  temporal_join <- amr_mat %>%
    select(sample = 1, `OXA-23`) %>%
    mutate(has_blaOXA23 = as.logical(`OXA-23`)) %>%
    select(sample, has_blaOXA23) %>%
    distinct(sample, .keep_all = TRUE)
} else {
  temporal_join <- tibble(sample = character(), has_blaOXA23 = logical())
}

# Master table
master <- meta
for (tbl in list(arg_count, annot, plasmid, prophage_sum, vfg_count, temporal_join)) {
  if (!is.null(tbl)) master <- full_join(master, tbl, by = "sample")
}
master <- master %>% mutate(across(where(is.numeric), ~replace_na(., 0)))

cat("Master table:", nrow(master), "\u00d7", ncol(master), "\n")

# ══════════════════════════════════════════════════════════════════════════════
# FIG 1 — ARG Burden by ST: Violin + Box + Jitter + Dunn p-values
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 1\n")

f1 <- master %>%
  filter(n_ARG_card > 0) %>%
  mutate(ST_Group = fct_reorder(ST_Group, n_ARG_card, median, .desc = TRUE))

kw1 <- tryCatch(kruskal_test(f1, n_ARG_card ~ ST_Group), error = function(e) NULL)

p1 <- ggplot(f1, aes(x = ST_Group, y = n_ARG_card, fill = ST_Group)) +
  geom_violin(trim = TRUE, alpha = 0.45, colour = NA) +
  geom_boxplot(width = 0.17, outlier.shape = NA, fill = "white",
               colour = "black", linewidth = 0.5) +
  geom_jitter(aes(colour = ST_Group), width = 0.13, size = 1.9,
              alpha = 0.8, show.legend = FALSE) +
  scale_fill_manual(values   = safe_pal(PAL_ST, unique(f1$ST_Group)), guide = "none") +
  scale_colour_manual(values = safe_pal(PAL_ST, unique(f1$ST_Group)), guide = "none") +
  labs(
    title    = "ARG Burden Across Sequence Types",
    subtitle = if (!is.null(kw1)) paste0("Kruskal-Wallis p = ", signif(kw1$p, 3),
                                          " | n = ", nrow(f1)) else paste("n =", nrow(f1)),
    x = "Sequence Type", y = "Number of ARGs (CARD)"
  ) + theme_pub()

if (!is.null(kw1) && n_distinct(f1$ST_Group) >= 2) {
  pwc <- tryCatch(
    dunn_test(f1, n_ARG_card ~ ST_Group, p.adjust.method = "BH") %>%
      add_xy_position(x = "ST_Group"),
    error = function(e) NULL
  )
  if (!is.null(pwc))
    p1 <- p1 + stat_pvalue_manual(pwc, label = "p.adj.signif",
                                  tip.length = 0.01, hide.ns = TRUE, size = 3.2)
}
save_fig(p1, "Fig01_ARG_by_ST", 7, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 2 — ARG Burden by Hospital: Barcode Range Plot
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 2\n")

all_locations <- sort(unique(master$location))

f2_summary <- master %>%
  filter(n_ARG_card > 0) %>%
  group_by(hospital, location) %>%
  summarise(n_isolates  = n(),
            min_arg     = min(n_ARG_card),
            max_arg     = max(n_ARG_card),
            median_arg  = median(n_ARG_card),
            .groups = "drop") %>%
  mutate(location   = factor(location, levels = all_locations),
         hosp_label = hospital)
f2_summary$hosp_label <- fct_reorder(f2_summary$hosp_label, f2_summary$median_arg)

f2_raw <- master %>%
  filter(n_ARG_card > 0) %>%
  mutate(location = factor(location, levels = all_locations)) %>%
  left_join(f2_summary %>% select(hospital, hosp_label), by = "hospital") %>%
  mutate(hosp_label = factor(hosp_label, levels = levels(f2_summary$hosp_label)))

kw2 <- tryCatch(kruskal_test(f2_raw, n_ARG_card ~ hospital), error = function(e) NULL)

p2 <- ggplot() +
  geom_linerange(data = f2_summary,
                 aes(y = hosp_label, xmin = min_arg, xmax = max_arg, color = location),
                 linewidth = 7, alpha = 0.25) +
  geom_point(data = f2_raw,
             aes(y = hosp_label, x = n_ARG_card, color = location),
             shape = 124, size = 4.5, alpha = 0.8) +
  geom_point(data = f2_summary,
             aes(y = hosp_label, x = median_arg, fill = location),
             shape = 21, size = 3.5, color = "white", stroke = 1) +
  geom_text(data = f2_summary,
            aes(y = hosp_label, x = max_arg, label = round(median_arg, 1)),
            hjust = -0.5, size = 3.5, fontface = "bold", color = "gray40") +
  scale_color_manual(values = safe_pal(PAL_LOC, all_locations), drop = FALSE, name = "Location") +
  scale_fill_manual(values  = safe_pal(PAL_LOC, all_locations), drop = FALSE, name = "Location") +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.15))) +
  labs(title    = "ARG Burden Across Hospitals",
       subtitle = if (!is.null(kw2)) paste0("Kruskal-Wallis p = ", signif(kw2$p, 3)) else "",
       x = "Number of ARGs (CARD)", y = "Hospital") +
  theme_pub() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "gray90", linetype = "dashed"),
        axis.text.y = element_text(face = "bold", size = 10))

save_fig(p2, "Fig02_ARG_by_Hospital", w = 9.5, h = 5.5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 3 — ARG Burden by Specimen Type
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 3\n")

f3 <- master %>%
  filter(n_ARG_card > 0, !is.na(specimen), specimen != "NA", specimen != "Unknown") %>%
  mutate(specimen = fct_reorder(specimen, n_ARG_card, median, .desc = TRUE))

kw3 <- tryCatch(kruskal_test(f3, n_ARG_card ~ specimen), error = function(e) NULL)

p3 <- ggplot(f3, aes(x = specimen, y = n_ARG_card, fill = specimen)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, linewidth = 0.5) +
  geom_jitter(aes(colour = specimen), width = 0.15, size = 2, alpha = 0.85,
              show.legend = FALSE) +
  scale_fill_manual(values   = safe_pal(PAL_SPEC, unique(f3$specimen)), guide = "none") +
  scale_colour_manual(values = safe_pal(PAL_SPEC, unique(f3$specimen)), guide = "none") +
  labs(title    = "ARG Burden by Specimen Type",
       subtitle = if (!is.null(kw3)) paste0("Kruskal-Wallis p = ", signif(kw3$p, 3)) else "",
       x = "Specimen Type", y = "Number of ARGs (CARD)") +
  theme_pub()

save_fig(p3, "Fig03_ARG_by_Specimen", 7, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 4 — Temporal ARG Trend: Line per hospital + blaOXA-23 emergence
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 4\n")

temp_plot <- master %>%
  filter(!is.na(year), year > 0, !is.na(n_ARG_card)) %>%
  group_by(hospital, year) %>%
  summarise(mean_ARG = mean(n_ARG_card), .groups = "drop")

oxa23_year <- master %>%
  filter(has_blaOXA23 == TRUE) %>%
  pull(year) %>% min(na.rm = TRUE)

hosp_pal4 <- safe_pal(PAL_HOSP, unique(temp_plot$hospital))

p4 <- ggplot(temp_plot, aes(x = year, y = mean_ARG,
                            group = hospital, colour = hospital)) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 2.4, shape = 21, fill = "white", stroke = 1) +
  scale_colour_manual(values = hosp_pal4, name = "Hospital") +
  scale_x_continuous(breaks = pretty_breaks(6)) +
  labs(title    = "Temporal Dynamics of ARG Accumulation",
       subtitle = "Mean ARG count per hospital per year",
       x = "Collection Year", y = "Mean ARG Count") +
  theme_pub()

if (is.finite(oxa23_year)) {
  p4 <- p4 +
    geom_vline(xintercept = oxa23_year, linetype = "dashed",
               colour = "grey25", linewidth = 0.6) +
    annotate("text", x = oxa23_year + 0.3, y = max(temp_plot$mean_ARG) * 0.9,
             label = "blaOXA-23 emerges", colour = "grey25", angle = 90,
             vjust = 0, size = 3.5, fontface = "italic")
}

save_fig(p4, "Fig04_Temporal_ARG_Dynamics_by_Hospital")

# ══════════════════════════════════════════════════════════════════════════════
# FIG 5 — ARG Ridge Plot: distribution shift over years
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 5\n")

f5 <- master %>%
  filter(!is.na(year), year > 0, n_ARG_card > 0) %>%
  mutate(Year = factor(year, levels = sort(unique(year))))

p5 <- ggplot(f5, aes(x = n_ARG_card, y = Year, fill = after_stat(x))) +
  geom_density_ridges_gradient(scale = 2, rel_min_height = 0.02,
                               colour = "white", linewidth = 0.3) +
  scale_fill_viridis_c(option = "C", name = "ARG Count") +
  scale_x_continuous(expand = c(0, 0)) +
  labs(title    = "ARG Burden Distribution Shift Over Time",
       subtitle = "Rightward shift signals increasing resistance accumulation",
       x = "Number of ARGs (CARD)", y = "Collection Year") +
  theme_pub() +
  theme(axis.line.y = element_blank(), axis.ticks.y = element_blank())

save_fig(p5, "Fig05_ARG_Ridge_Temporal", 7, 6)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 6 — ARG by Era (Early / Mid / Recent) + specimen overlay
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 6\n")

f6 <- master %>%
  filter(n_ARG_card > 0, !is.na(era), era != "Unknown") %>%
  mutate(era = factor(era, levels = c("Early (\u22642010)","Mid (2011-2017)","Recent (2018-2020)")))

kw6  <- tryCatch(kruskal_test(f6, n_ARG_card ~ era), error = function(e) NULL)
pwc6 <- tryCatch(
  dunn_test(f6, n_ARG_card ~ era, p.adjust.method = "BH") %>%
    add_xy_position(x = "era"),
  error = function(e) NULL
)

p6 <- ggplot(f6, aes(x = era, y = n_ARG_card, fill = era)) +
  geom_violin(alpha = 0.45, colour = NA, trim = TRUE) +
  geom_boxplot(width = 0.16, outlier.shape = NA, fill = "white",
               colour = "black", linewidth = 0.5) +
  geom_jitter(aes(colour = specimen), width = 0.13, size = 2.1, alpha = 0.85) +
  scale_fill_manual(values   = c("#A8DADC","#457B9D","#E63946"), guide = "none") +
  scale_colour_manual(values = safe_pal(PAL_SPEC, unique(f6$specimen)), name = "Specimen") +
  labs(title    = "ARG Accumulation Across Eras",
       subtitle = if (!is.null(kw6)) paste0("Kruskal-Wallis p = ", signif(kw6$p, 3)) else "",
       x = "Era", y = "Number of ARGs") +
  theme_pub()

if (!is.null(pwc6))
  p6 <- p6 + stat_pvalue_manual(pwc6, label = "p.adj.signif",
                                tip.length = 0.01, hide.ns = TRUE, size = 3.2)
save_fig(p6, "Fig06_ARG_by_Era", 8, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 7 — Genome Size vs ARG: Scatter + regression + ST colour
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 7\n")

f7 <- master %>%
  filter(genome_size_bp > 0, n_ARG_card > 0) %>%
  mutate(genome_size_mbp = genome_size_bp / 1e6)

cor7 <- cor.test(f7$genome_size_mbp, f7$n_ARG_card, method = "spearman", exact = FALSE)

p7 <- ggplot(f7, aes(x = genome_size_bp / 1e6, y = n_ARG_card, colour = ST_Group)) +
  geom_point(size = 2.3, alpha = 0.78) +
  geom_smooth(method = "lm", colour = "grey20", linewidth = 0.7, se = TRUE, fill = "grey85") +
  geom_label_repel(
    data = f7 %>% filter(n_ARG_card >= quantile(n_ARG_card, 0.88, na.rm = TRUE)),
    aes(label = sample), size = 2.4, max.overlaps = 12,
    box.padding = 0.3, segment.colour = "grey60", show.legend = FALSE
  ) +
  scale_colour_manual(values = safe_pal(PAL_ST, unique(f7$ST_Group)), name = "ST") +
  annotate("text",
           x = quantile(f7$genome_size_bp / 1e6, 0.58, na.rm = TRUE),
           y = max(f7$n_ARG_card) * 0.97,
           label = sprintf("Spearman \u03c1 = %.2f\np = %.3f", cor7$estimate, cor7$p.value),
           size = 3.5, hjust = 0, fontface = "italic") +
  labs(title    = "Genome Size vs ARG Burden",
       subtitle = paste0("Spearman \u03c1 = ", round(cor7$estimate, 2),
                         " | p = ", signif(cor7$p.value, 3)),
       x = "Genome Size (Mbp)", y = "Total ARG Count") +
  theme_pub()

save_fig(p7, "Fig07_Genome_vs_ARG", 8, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 8 — Plasmid Count vs ARG Count
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 8\n")

f8 <- master %>% filter(n_plasmid_contigs > 0 | n_ARG_card > 0)
cor8 <- cor.test(f8$n_plasmid_contigs, f8$n_ARG_card, method = "spearman", exact = FALSE)

p8 <- ggplot(f8, aes(x = n_plasmid_contigs, y = n_ARG_card, colour = hospital)) +
  geom_point(size = 2.5, alpha = 0.82) +
  geom_smooth(method = "lm", colour = "grey20", se = TRUE,
              fill = "grey85", linewidth = 0.7) +
  geom_label_repel(
    data = f8 %>% filter(n_ARG_card >= quantile(f8$n_ARG_card, 0.85, na.rm = TRUE)),
    aes(label = sample), size = 2.3, max.overlaps = 10,
    box.padding = 0.3, segment.colour = "grey60", show.legend = FALSE
  ) +
  scale_colour_manual(values = safe_pal(PAL_HOSP, unique(f8$hospital)), name = "Hospital") +
  annotate("text",
           x = max(f8$n_plasmid_contigs, na.rm = TRUE) * 0.55,
           y = max(f8$n_ARG_card) * 0.97,
           label = sprintf("Spearman \u03c1 = %.2f\np = %.3f", cor8$estimate, cor8$p.value),
           size = 3.5, hjust = 0, fontface = "italic") +
  labs(title    = "Plasmid-Driven ARG Acquisition",
       subtitle = paste0("Spearman \u03c1 = ", round(cor8$estimate, 2),
                         " | p = ", signif(cor8$p.value, 3)),
       x = "Number of Plasmid Contigs", y = "Total ARG Count") +
  theme_pub()

save_fig(p8, "Fig08_Plasmid_vs_ARG", 8, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 9 — IS–ARG Physical Distance Histogram + Density
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 9\n")

if (!is.null(is_arg_link) && nrow(is_arg_link) > 0) {
  pct1kb <- mean(is_arg_link$distance_bp < 1000, na.rm = TRUE) * 100
  pct500 <- mean(is_arg_link$distance_bp < 500,  na.rm = TRUE) * 100

  p9 <- ggplot(is_arg_link %>% filter(!is.na(distance_bp)),
               aes(x = distance_bp / 1000)) +
    geom_histogram(aes(y = after_stat(density)), binwidth = 0.3,
                   fill = "#E63946", colour = "white", linewidth = 0.2) +
    geom_density(colour = "#1D3557", linewidth = 0.85, adjust = 1.5) +
    geom_vline(xintercept = 1, linetype = "dashed", colour = "grey25", linewidth = 0.6) +
    annotate("text", x = 1.08, y = Inf, label = "1 kb",
             vjust = 1.4, hjust = 0, size = 3, colour = "grey25") +
    annotate("text",
             x = max(is_arg_link$distance_bp, na.rm = TRUE) / 1000 * 0.5, y = Inf,
             label = sprintf("%.0f%% < 1 kb\n%.0f%% < 500 bp", pct1kb, pct500),
             vjust = 1.6, hjust = 0, size = 3.8, fontface = "bold", colour = "#E63946") +
    labs(title    = "IS Element\u2013ARG Physical Distance",
         subtitle = "Close proximity = strong evidence of IS-mediated co-mobilisation",
         x = "Distance (kb)", y = "Density") +
    theme_pub()
  save_fig(p9, "Fig09_IS_ARG_Distance", 7, 5)
} else { cat("   [SKIP] Fig 9 — IS_ARG_linkage.tsv not available\n") }

# ══════════════════════════════════════════════════════════════════════════════
# FIG 10 — IS Family Prevalence: Lollipop
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 10\n")

if (!is.null(is_freq) && nrow(is_freq) > 0) {
  is_sum <- is_freq %>%
    group_by(IS_family) %>%
    summarise(prev   = mean(count > 0, na.rm = TRUE) * 100,
              mean_n = mean(count, na.rm = TRUE), .groups = "drop") %>%
    filter(prev > 5) %>%
    mutate(IS_family = fct_reorder(IS_family, prev))

  p10 <- ggplot(is_sum, aes(x = prev, y = IS_family)) +
    geom_segment(aes(x = 0, xend = prev, y = IS_family, yend = IS_family),
                 colour = "grey75", linewidth = 0.6) +
    geom_point(aes(size = mean_n, colour = prev)) +
    scale_colour_viridis_c(option = "C", name = "Prevalence (%)") +
    scale_size_continuous(range = c(2, 9), name = "Mean copy no.") +
    scale_x_continuous(limits = c(0, 108), labels = function(x) paste0(x, "%")) +
    labs(title    = "Insertion Sequence Family Prevalence",
         subtitle = "Point size = mean copy number per positive isolate",
         x = "Isolate Prevalence (%)", y = NULL) +
    theme_pub() +
    theme(axis.line.y = element_blank(), axis.ticks.y = element_blank())
  save_fig(p10, "Fig10_IS_Prevalence", 7, 5.5)
} else { cat("   [SKIP] Fig 10 — IS_family_frequency.tsv not available\n") }

# ══════════════════════════════════════════════════════════════════════════════
# FIG 11 — IS Burden vs ARG Burden per isolate
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 11\n")

if (!is.null(is_freq) && nrow(is_freq) > 0) {
  is_total <- is_freq %>%
    group_by(sample) %>%
    summarise(n_IS_total = sum(count, na.rm = TRUE), .groups = "drop")

  f11  <- master %>% left_join(is_total, by = "sample") %>%
    filter(n_ARG_card > 0, n_IS_total > 0)
  cor11 <- cor.test(f11$n_IS_total, f11$n_ARG_card, method = "spearman", exact = FALSE)

  p11 <- ggplot(f11, aes(x = n_IS_total, y = n_ARG_card, colour = ST_Group)) +
    geom_point(size = 2.4, alpha = 0.82) +
    geom_smooth(method = "lm", colour = "grey20", se = TRUE,
                fill = "grey85", linewidth = 0.7) +
    geom_label_repel(
      data = f11 %>% filter(n_ARG_card >= quantile(f11$n_ARG_card, 0.85, na.rm = TRUE)),
      aes(label = sample), size = 2.3, max.overlaps = 10,
      box.padding = 0.3, segment.colour = "grey60", show.legend = FALSE
    ) +
    scale_colour_manual(values = safe_pal(PAL_ST, unique(f11$ST_Group)), name = "ST") +
    annotate("text",
             x = max(f11$n_IS_total, na.rm = TRUE) * 0.55,
             y = max(f11$n_ARG_card) * 0.97,
             label = sprintf("Spearman \u03c1 = %.2f\np = %.3f", cor11$estimate, cor11$p.value),
             size = 3.5, hjust = 0, fontface = "italic") +
    labs(title    = "IS Element Burden vs ARG Count",
         subtitle = "Higher IS density \u2192 greater ARG accumulation",
         x = "Total IS Element Count", y = "Total ARG Count (CARD)") +
    theme_pub()
  save_fig(p11, "Fig11_IS_vs_ARG", 8, 5)
} else { cat("   [SKIP] Fig 11 — IS data not available\n") }

# ══════════════════════════════════════════════════════════════════════════════
# FIG 12 — AMR Heatmap: Presence/Absence with ST + hospital annotation
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 12\n")

if (!is.null(amr_mat)) {
  amr_matrix <- amr_mat %>%
    column_to_rownames(names(amr_mat)[1]) %>%
    mutate(across(everything(), ~replace_na(suppressWarnings(as.numeric(.)), 0))) %>%
    as.matrix()

  ann_df <- meta %>%
    select(sample, ST_Group, hospital, era) %>%
    filter(sample %in% rownames(amr_matrix)) %>%
    column_to_rownames("sample")
  ann_df <- ann_df[rownames(amr_matrix), , drop = FALSE]

  era_pal   <- c("Early (\u22642010)"="#A8DADC","Mid (2011-2017)"="#457B9D",
                 "Recent (2018-2020)"="#E63946")
  ann_cols  <- list(
    ST_Group = safe_pal(PAL_ST,   unique(ann_df$ST_Group)),
    hospital = safe_pal(PAL_HOSP, unique(ann_df$hospital)),
    era      = era_pal[names(era_pal) %in% unique(ann_df$era)]
  )

  pheatmap(
    amr_matrix,
    annotation_row    = ann_df,
    annotation_colors = ann_cols,
    color             = colorRampPalette(c("white","#457B9D","#E63946"))(50),
    border_color      = NA,
    treeheight_row    = 25, treeheight_col = 25,
    fontsize_row      = 6,  fontsize_col   = 7,
    clustering_distance_rows = "binary",
    clustering_distance_cols = "binary",
    clustering_method = "ward.D2",
    main              = "AMR Gene Presence/Absence Matrix",
    filename          = file.path(FIG_DIR, "Fig12_AMR_Heatmap.pdf"),
    width = 13, height = 10
  )
  cat("   \u2714 Fig12_AMR_Heatmap\n")
} else { cat("   [SKIP] Fig 12 — amr_matrix.csv not available\n") }

# ══════════════════════════════════════════════════════════════════════════════
# FIG 13 — Plasmid Mobility by ST: Stacked bar
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 13\n")

if (!is.null(mob_suite) && "predicted_mobility" %in% names(mob_suite)) {
  mob_st <- mob_suite %>%
    left_join(meta %>% select(sample, ST_Group, hospital), by = "sample") %>%
    filter(!is.na(predicted_mobility)) %>%
    count(ST_Group, predicted_mobility) %>%
    group_by(ST_Group) %>%
    mutate(prop = n / sum(n)) %>% ungroup()

  mob_pal <- c("conjugative"="#E63946","mobilizable"="#457B9D",
               "non-mobilizable"="#A8DADC","reported"="#F4A261")

  p13 <- ggplot(mob_st, aes(x = ST_Group, y = prop, fill = predicted_mobility)) +
    geom_bar(stat = "identity", colour = "white", linewidth = 0.3) +
    scale_y_continuous(labels = scales::percent) +
    scale_fill_manual(values = safe_pal(mob_pal, unique(mob_st$predicted_mobility)),
                      name = "Mobility") +
    labs(title    = "Plasmid Mobility Classes by Sequence Type",
         subtitle = "MOB-suite classification",
         x = "Sequence Type", y = "Proportion of Plasmids") +
    theme_pub()
  save_fig(p13, "Fig13_Plasmid_Mobility_ST", 7, 5)
} else { cat("   [SKIP] Fig 13 — mob_suite_summary.tsv not available\n") }

# ══════════════════════════════════════════════════════════════════════════════
# FIG 14 — Prophage Burden per Isolate
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 14\n")

if (!is.null(prophage_sum)) {
  f14 <- prophage_sum %>%
    left_join(meta %>% select(sample, ST_Group, hospital), by = "sample") %>%
    filter(!is.na(n_virus_contigs)) %>%
    mutate(sample = fct_reorder(sample, n_virus_contigs))

  p14 <- ggplot(f14, aes(x = sample, y = n_virus_contigs, fill = ST_Group)) +
    geom_col() +
    scale_fill_manual(values = safe_pal(PAL_ST, unique(f14$ST_Group)), name = "ST") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
    labs(title = "Prophage Burden per Isolate", subtitle = "Ordered by prophage count",
         x = NULL, y = "Prophage Contigs") +
    theme_pub() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 6))
  save_fig(p14, "Fig14_Prophage_Burden", 11, 5)
}

# ══════════════════════════════════════════════════════════════════════════════
# FIG 15 — Prophage ARG Carriage: Donut chart
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 15\n")

if (!is.null(prophage_sum) && !is.null(prophage_arg)) {
  total_prophages       <- sum(prophage_sum$n_provirus, na.rm = TRUE)
  arg_carrying_prophages <- n_distinct(prophage_arg$phage_contig)

  ph_stat <- tibble(
    status = c("ARG-carrying", "ARG-free"),
    n      = c(arg_carrying_prophages, max(0, total_prophages - arg_carrying_prophages))
  ) %>%
    mutate(prop  = n / sum(n),
           label = paste0(status, "\n(n=", n, ", ", scales::percent(prop, 0.1), ")"))

  p15 <- ggplot(ph_stat, aes(x = 2, y = prop, fill = status)) +
    geom_bar(stat = "identity", width = 1, colour = "white", linewidth = 0.8) +
    coord_polar(theta = "y") + xlim(0.5, 2.5) +
    geom_text(aes(label = label), position = position_stack(vjust = 0.5), size = 4) +
    scale_fill_manual(values = c("ARG-carrying"="#E63946","ARG-free"="#A8DADC"),
                      guide = "none") +
    labs(title    = "Prophage ARG Carriage",
         subtitle = "Prophages are predominantly ARG-free") +
    theme_void(base_size = 12) +
    theme(plot.title    = element_text(size=13, face="bold", hjust=0.5, margin=margin(b=4)),
          plot.subtitle = element_text(size=10, colour="grey40", hjust=0.5))
  save_fig(p15, "Fig15_Prophage_ARG_Donut", 5, 5)
} else { cat("   [SKIP] Fig 15 — prophage data not available\n") }

# ══════════════════════════════════════════════════════════════════════════════
# FIG 16 — VFG Count by ST + specimen
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 16\n")

f16 <- master %>%
  filter(n_VFG_total > 0) %>%
  mutate(ST_Group = fct_reorder(ST_Group, n_VFG_total, median, .desc = TRUE))

p16 <- ggplot(f16, aes(x = ST_Group, y = n_VFG_total, fill = ST_Group)) +
  geom_violin(alpha = 0.45, colour = NA, trim = TRUE) +
  geom_boxplot(width = 0.17, outlier.shape = NA, fill = "white",
               colour = "black", linewidth = 0.5) +
  geom_jitter(aes(colour = specimen), width = 0.13, size = 2, alpha = 0.85) +
  scale_fill_manual(values   = safe_pal(PAL_ST,   unique(f16$ST_Group)), guide = "none") +
  scale_colour_manual(values = safe_pal(PAL_SPEC, unique(f16$specimen)), name = "Specimen") +
  labs(title    = "Virulence Factor Gene Count by Sequence Type",
       subtitle = paste(nrow(f16), "isolates with VFG data"),
       x = "Sequence Type", y = "Total VFG Count") +
  theme_pub()

save_fig(p16, "Fig16_VFG_by_ST", 7, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 17 — ARG vs VFG Correlation
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 17\n")

f17  <- master %>% filter(n_ARG_card > 0, n_VFG_total > 0)
cor17 <- cor.test(f17$n_ARG_card, f17$n_VFG_total, method = "spearman", exact = FALSE)

p17 <- ggplot(f17, aes(x = n_ARG_card, y = n_VFG_total, colour = hospital)) +
  geom_point(size = 2.3, alpha = 0.82) +
  geom_smooth(method = "lm", colour = "grey20", se = TRUE, fill = "grey85", linewidth = 0.7) +
  geom_label_repel(
    data = f17 %>% filter(n_ARG_card > quantile(n_ARG_card,0.85,na.rm=TRUE) |
                            n_VFG_total > quantile(n_VFG_total,0.85,na.rm=TRUE)),
    aes(label = sample), size = 2.3, max.overlaps = 10,
    box.padding = 0.3, segment.colour = "grey60", show.legend = FALSE
  ) +
  scale_colour_manual(values = safe_pal(PAL_HOSP, unique(f17$hospital)), name = "Hospital") +
  annotate("text",
           x = max(f17$n_ARG_card) * 0.55, y = max(f17$n_VFG_total) * 0.97,
           label = sprintf("Spearman \u03c1 = %.2f\np = %.3f", cor17$estimate, cor17$p.value),
           size = 3.5, hjust = 0, fontface = "italic") +
  labs(title    = "ARG Burden vs Virulence Factor Count",
       subtitle = "Co-pathogenicity axis: high-ARG isolates also carry more VFGs",
       x = "ARG Count (CARD)", y = "Virulence Factor Gene Count") +
  theme_pub()

save_fig(p17, "Fig17_ARG_vs_VFG", 8, 5)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 18 — Spearman Correlation Matrix (all genomic features)
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 18\n")

is_total_cor <- if (!is.null(is_freq) && nrow(is_freq) > 0)
  is_freq %>% group_by(sample) %>% summarise(n_IS_total = sum(count, na.rm=TRUE), .groups="drop")
else tibble(sample=character(), n_IS_total=numeric())

master_cor <- master %>% left_join(is_total_cor, by = "sample")

cor_vars <- master_cor %>%
  select(where(is.numeric)) %>%
  select(-any_of("year")) %>%
  select(where(~sd(., na.rm=TRUE) > 0))

if (ncol(cor_vars) >= 2) {
  cor_mat  <- cor(cor_vars, method = "spearman", use = "pairwise.complete.obs")
  cor_pmat <- ggcorrplot::cor_pmat(cor_vars, method = "spearman") %>%
    column_to_rownames("rowname") %>% as.matrix()

  clean_labels <- colnames(cor_vars) %>%
    str_replace_all("n_","") %>% str_replace_all("_"," ") %>% str_to_title()
  colnames(cor_mat)  <- rownames(cor_mat)  <- clean_labels
  colnames(cor_pmat) <- rownames(cor_pmat) <- clean_labels

  pdf(file.path(FIG_DIR,"Fig18_Correlation_Matrix.pdf"), width=9, height=8)
  corrplot(cor_mat, p.mat=cor_pmat, method="color", type="upper",
           order="hclust", sig.level=0.05, insig="blank",
           addCoef.col="black", number.cex=0.62,
           tl.col="black", tl.srt=45, tl.cex=0.78, cl.cex=0.75,
           col=colorRampPalette(c("#457B9D","white","#E63946"))(100),
           title="Spearman Correlation \u2014 Genomic Features", mar=c(0,0,2,0))
  dev.off()
  cat("   \u2714 Fig18_Correlation_Matrix\n")
}

# ══════════════════════════════════════════════════════════════════════════════
# FIG 19 — Alluvial: Hospital → ST → Specimen
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 19\n")

f19 <- master %>%
  filter(!is.na(hospital), !is.na(ST_Group), !is.na(specimen)) %>%
  mutate(oxa23_status = ifelse(has_blaOXA23 == 1, "blaOXA-23+", "blaOXA-23\u2212"),
         specimen     = ifelse(specimen %in% c("NA","Unknown"), "Unknown", specimen)) %>%
  count(hospital, ST_Group, specimen, oxa23_status)

p19 <- ggplot(f19, aes(axis1=hospital, axis2=ST_Group, axis3=specimen, y=n)) +
  geom_alluvium(aes(fill = ST_Group), alpha = 0.7, width = 0.3) +
  geom_stratum(width = 0.3, fill = "grey92", colour = "grey50", linewidth = 0.3) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum)),
             size = 2.8, label.padding = unit(0.15,"lines"), label.size = 0) +
  scale_fill_manual(values = safe_pal(PAL_ST, unique(f19$ST_Group)), name = "ST Group") +
  scale_x_discrete(limits = c("Hospital","ST","Specimen"), expand = c(0.05, 0.05)) +
  labs(title    = "Epidemiological Flow: Hospital \u2192 ST \u2192 Specimen",
       subtitle = "Stream width proportional to isolate count",
       x = NULL, y = "Isolate Count") +
  theme_pub() +
  theme(axis.line.x = element_blank(), axis.ticks.x = element_blank())

save_fig(p19, "Fig19_Alluvial_Flow", 10, 7)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 20 — MLST Bubble: ST × Year × Hospital
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 20\n")

mlst_plot <- meta %>%
  filter(!is.na(ST_val), !is.na(year), year > 0) %>%
  count(ST_Group, hospital, year)

p20 <- ggplot(mlst_plot, aes(x = year, y = ST_Group, size = n, colour = hospital)) +
  geom_point(alpha = 0.80) +
  scale_size_continuous(range = c(2, 13), name = "Isolate count") +
  scale_colour_manual(values = trimws(safe_pal(PAL_HOSP, unique(mlst_plot$hospital))),
                      name = "Hospital") +
  scale_x_continuous(breaks = scales::pretty_breaks(6)) +
  labs(title    = "MLST Sequence Type Distribution Over Time",
       subtitle = "Bubble size = isolate count per ST per year",
       x = "Collection Year", y = "Sequence Type") +
  theme_pub()

save_fig(p20, "Fig20_MLST_Bubble", 9, 6)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 21 — Treemap: Specimen × Hospital
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 21\n")

f21 <- meta %>%
  filter(!is.na(specimen), !specimen %in% c("NA","Unknown")) %>%
  count(hospital, specimen) %>%
  mutate(label = paste0(specimen,"\n(n=",n,")"))

p21 <- ggplot(f21, aes(area=n, fill=hospital, label=label, subgroup=hospital)) +
  treemapify::geom_treemap(colour="white", linewidth=0.6) +
  treemapify::geom_treemap_subgroup_border(colour="grey20", linewidth=1.2) +
  treemapify::geom_treemap_subgroup_text(place="topleft", size=9,
                                         colour="grey15", fontface="bold",
                                         padding.x=unit(2,"mm"), padding.y=unit(2,"mm")) +
  treemapify::geom_treemap_text(colour="white", size=7.5, place="centre",
                                reflow=TRUE, padding.x=unit(1.5,"mm")) +
  scale_fill_manual(values=safe_pal(PAL_HOSP, unique(f21$hospital)), name="Hospital") +
  labs(title="Isolate Distribution by Hospital and Specimen Type",
       subtitle="Area proportional to isolate count") +
  theme_pub() +
  theme(axis.line=element_blank(), axis.ticks=element_blank(),
        axis.text=element_blank(), axis.title=element_blank())

save_fig(p21, "Fig21_Treemap_Hospital_Specimen", 9, 6)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 22 — Multivariable Forest Plot: ARG predictors
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 22\n")

lm_vars <- master_cor %>%
  select(n_ARG_card, n_plasmid_contigs, n_IS_total, n_VFG_total,
         genome_size_bp, n_virus_contigs, ST_Group, era) %>%
  drop_na()

lm_fit <- NULL
if (nrow(lm_vars) >= 10) {
  lm_fit <- lm(n_ARG_card ~ n_plasmid_contigs + n_IS_total + n_VFG_total +
                 genome_size_bp + n_virus_contigs + ST_Group + era,
               data = lm_vars)

  forest_df <- broom::tidy(lm_fit, conf.int = TRUE) %>%
    filter(term != "(Intercept)") %>%
    drop_na(estimate) %>%
    mutate(term      = str_replace_all(term, "ST_Group|era","") %>%
             str_replace_all("_"," ") %>% str_to_title(),
           sig       = case_when(p.value < 0.001 ~ "***", p.value < 0.01 ~ "**",
                                 p.value < 0.05  ~ "*",   TRUE           ~ "ns"),
           direction = ifelse(estimate > 0, "Positive", "Negative"))

  p22 <- ggplot(forest_df,
                aes(x=estimate, y=fct_reorder(term, estimate), colour=direction)) +
    geom_vline(xintercept=0, linetype="dashed", colour="grey40", linewidth=0.6) +
    geom_errorbarh(aes(xmin=conf.low, xmax=conf.high), height=0.25, linewidth=0.6) +
    geom_point(size=3) +
    geom_text(aes(label=sig, x=conf.high + 0.3), size=3.5, hjust=0, colour="grey20") +
    scale_colour_manual(values=c("Positive"="#E63946","Negative"="#457B9D"),
                        name="Direction") +
    labs(title    = "Independent Predictors of ARG Burden",
         subtitle = sprintf("Multiple linear regression | R\u00b2 = %.2f | p = %.3f",
                            summary(lm_fit)$r.squared,
                            pf(summary(lm_fit)$fstatistic[1],
                               summary(lm_fit)$fstatistic[2],
                               summary(lm_fit)$fstatistic[3], lower.tail=FALSE)),
         x="Regression Coefficient (95% CI)", y=NULL) +
    theme_pub()
  save_fig(p22, "Fig22_Forest_ARG_Predictors", 8, 6)
}

# ══════════════════════════════════════════════════════════════════════════════
# FIG 23 — SNP Phylogeny annotated with ST, hospital, year, ARG bar
# ══════════════════════════════════════════════════════════════════════════════
cat("Fig 23\n")

tree_file <- file.path(RESULTS_DIR, "09_SNP_phylogeny", "iqtree",
                       "acinetobacter_snp.treefile")

if (file.exists(tree_file)) {
  tree <- read.tree(tree_file)
  tree$tip.label <- gsub("\\..*$", "", tree$tip.label)
  tree <- midpoint.root(tree)

  ann_tree <- master %>%
    select(sample, ST_Group, hospital, year, n_ARG_card) %>%
    filter(sample %in% tree$tip.label) %>%
    mutate(year = as.character(year))

  p23 <- ggtree(tree, layout="rectangular", size=0.65,
                branch.length="branch.length") %<+% ann_tree +
    geom_treescale(x=0.005, y=2, fontsize=3, linesize=0.6) +
    geom_tippoint(aes(colour=ST_Group), size=3.4, alpha=0.95) +
    geom_tippoint(aes(colour=hospital), size=2.9, shape=21, fill="white", stroke=1) +
    geom_tiplab(aes(label=paste0(year)),
                size=2.9, offset=0.032, align=TRUE, hjust=0, linesize=0.35) +
    geom_fruit(
      geom=geom_col,
      mapping=aes(x=n_ARG_card, fill=ST_Group),
      pwidth=1.2, offset=0.3,
      axis.params=list(axis="x", title="ARG count", title.size=3.5,
                       title.height=0.07, text.size=3.2)
    ) +
    scale_colour_manual(values=safe_pal(PAL_ST,   unique(ann_tree$ST_Group)), name="ST Group") +
    scale_fill_manual(values  =safe_pal(PAL_ST,   unique(ann_tree$ST_Group)), name="ST Group") +
    scale_colour_manual(values=safe_pal(PAL_HOSP, unique(ann_tree$hospital)), name="Hospital",
                        guide=guide_legend(override.aes=list(size=4.5))) +
    labs(title="SNP-based Phylogeny of A. baumannii Isolates") +
    theme_pub() +
    theme(legend.position="right", legend.box="vertical",
          plot.margin=margin(10,60,60,10),
          axis.title.x=element_text(vjust=-18, margin=margin(t=40), size=11, face="bold"),
          plot.title=element_text(margin=margin(b=30), hjust=0.5)) +
    xlim_tree(0.42)

  save_fig(p23, "Fig23_SNP_Phylogeny_Annotated", w=18, h=12)
  write.tree(tree, file=file.path(FIG_DIR, "Fig23_acinetobacter_midpoint_clean.nwk"))
} else {
  cat("   [SKIP] Fig 23 — tree file not found:", tree_file, "\n")
  cat("         Run step08_SNP_phylogeny.sh first.\n")
}

# ══════════════════════════════════════════════════════════════════════════════
# STATISTICS OUTPUT
# ══════════════════════════════════════════════════════════════════════════════
cat("\n Generating statistics report...\n")

stat_data <- master_cor %>% filter(n_ARG_card > 0)

sink(file.path(FIG_DIR, "advanced_statistics.txt"))
cat("ACINETOBACTER BAUMANNII \u2014 ADVANCED STATISTICS\n")
cat(strrep("=", 65), "\n\n")

cat("1. ST_Group Distribution:\n"); print(table(meta$ST_Group, useNA="always"))

grps <- stat_data %>% count(ST_Group) %>% filter(n >= 2) %>% pull(ST_Group)
if (length(grps) >= 2) {
  kw <- kruskal_test(filter(stat_data, ST_Group %in% grps), n_ARG_card ~ ST_Group)
  cat("\n2. Kruskal-Wallis ARG ~ ST:\n"); print(kw)
  dunn <- dunn_test(filter(stat_data, ST_Group %in% grps),
                    n_ARG_card ~ ST_Group, p.adjust.method="BH")
  cat("\n   Dunn post-hoc:\n")
  print(dunn %>% select(group1, group2, p.adj, p.adj.signif))
}

kw_era <- kruskal_test(filter(stat_data, !is.na(era), era != "Unknown"), n_ARG_card ~ era)
cat("\n3. Kruskal-Wallis ARG ~ Era:\n"); print(kw_era)
dunn_era <- dunn_test(filter(stat_data, !is.na(era), era != "Unknown"),
                      n_ARG_card ~ era, p.adjust.method="BH")
cat("   Dunn:\n"); print(dunn_era %>% select(group1, group2, p.adj, p.adj.signif))

f_spec <- stat_data %>% filter(!is.na(specimen), !specimen %in% c("NA","Unknown"))
kw_sp  <- tryCatch(kruskal_test(f_spec, n_ARG_card ~ specimen), error=function(e) NULL)
cat("\n4. Kruskal-Wallis ARG ~ Specimen:\n"); print(kw_sp)

cat("\n5. Spearman Correlations:\n")
cors <- list(
  "Plasmid x ARG"    = cor.test(master_cor$n_plasmid_contigs, master_cor$n_ARG_card,  method="spearman", exact=FALSE),
  "IS x ARG"         = cor.test(master_cor$n_IS_total,         master_cor$n_ARG_card,  method="spearman", exact=FALSE),
  "VFG x ARG"        = cor.test(master_cor$n_VFG_total,         master_cor$n_ARG_card, method="spearman", exact=FALSE),
  "GenomeSize x ARG" = cor.test(master_cor$genome_size_bp,       master_cor$n_ARG_card, method="spearman", exact=FALSE),
  "Prophage x ARG"   = cor.test(master_cor$n_virus_contigs,      master_cor$n_ARG_card, method="spearman", exact=FALSE)
)
for (nm in names(cors)) {
  r <- cors[[nm]]
  cat(sprintf("   %-22s rho = %6.3f  p = %.4f\n", nm, r$estimate, r$p.value))
}

if (!is.null(is_arg_link) && nrow(is_arg_link) > 0) {
  cat("\n6. IS-ARG Distance Quantiles (bp):\n")
  print(quantile(is_arg_link$distance_bp, probs=c(.25,.50,.75,.90,.95), na.rm=TRUE))
  cat(sprintf("   <1kb: %.1f%%  |  <500bp: %.1f%%\n",
              mean(is_arg_link$distance_bp < 1000, na.rm=TRUE)*100,
              mean(is_arg_link$distance_bp < 500,  na.rm=TRUE)*100))
}

if (!is.null(mob_suite) && "predicted_mobility" %in% names(mob_suite) && "size" %in% names(mob_suite)) {
  mob_t <- mob_suite %>%
    filter(predicted_mobility %in% c("conjugative","mobilizable"), !is.na(size))
  if (nrow(mob_t) >= 4) {
    wt <- wilcox.test(size ~ predicted_mobility, data=mob_t, exact=FALSE)
    cat("\n7. Conjugative vs Mobilizable Plasmid Size (bp):\n")
    print(mob_t %>% group_by(predicted_mobility) %>%
            summarise(median_size=median(size), n=n(), .groups="drop"))
    cat(sprintf("   W=%.0f, p=%.4f\n", wt$statistic, wt$p.value))
  }
}

oxa_tab <- master %>%
  filter(!is.na(has_blaOXA23), !is.na(hospital)) %>%
  count(hospital, has_blaOXA23)
if (nrow(oxa_tab) >= 4) {
  oxa_xt  <- xtabs(n ~ hospital + has_blaOXA23, data=oxa_tab)
  oxa_chi <- tryCatch(chisq.test(oxa_xt, simulate.p.value=TRUE),
                      error=function(e) fisher.test(oxa_xt, simulate.p.value=TRUE))
  cat("\n8. blaOXA-23 chi-squared by hospital:\n"); print(oxa_chi)
}

cat("\n9. Multivariable Regression (ARG ~ all predictors):\n")
if (!is.null(lm_fit)) {
  print(broom::tidy(lm_fit, conf.int=TRUE) %>%
          mutate(across(where(is.numeric), ~round(., 4))))
  cat(sprintf("   R2 = %.3f | Adj-R2 = %.3f\n",
              summary(lm_fit)$r.squared, summary(lm_fit)$adj.r.squared))
} else {
  cat("   Skipped: insufficient data for regression.\n")
}

cat("\n10. Effect Size (Cohen's d) — Recent vs Early era:\n")
cd <- tryCatch(
  cohens_d(filter(stat_data, era %in% c("Early (\u22642010)","Recent (2018-2020)")),
           n_ARG_card ~ era),
  error = function(e) cat("   Not enough data\n")
)
print(cd)

cat("\n11. Descriptive Summary by ST Group:\n")
print(stat_data %>%
        group_by(ST_Group) %>%
        summarise(n=n(), Mean=round(mean(n_ARG_card),1),
                  Median=median(n_ARG_card), SD=round(sd(n_ARG_card),1),
                  IQR=IQR(n_ARG_card), Min=min(n_ARG_card), Max=max(n_ARG_card),
                  .groups="drop") %>%
        arrange(desc(Median)))

sink()
cat("   \u2714 advanced_statistics.txt\n")

# Save master merged table
write_csv(master, file.path(SUM_DIR, "master_merged_data.csv"))
cat("   \u2714 master_merged_data.csv\n")

# ══════════════════════════════════════════════════════════════════════════════
# DONE
# ══════════════════════════════════════════════════════════════════════════════
cat("\n\n\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\n")
cat("ALL 23 FIGURES + STATISTICS COMPLETE\n")
cat("\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\n")
cat("Output directory:", FIG_DIR, "\n\n")
for (f in list.files(FIG_DIR, pattern="\\.(pdf|png|txt|nwk)$"))
  cat(" \u2022", f, "\n")
