#!/usr/bin/env bash
# =============================================================================
# STEP 00 — Project Setup: Directory Structure & Sample List
# Paper: Kumkar et al. 2022 (Front. Cell. Infect. Microbiol.) — Replication + Extension
# =============================================================================
# Creates the full output directory tree and generates the sample list used
# by all downstream steps. Run this FIRST before any other step.
# Reads paths from config.sh in the same directory.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── LOAD USER CONFIG ────────────────────────────────────────────────────────
if [[ ! -f "$SCRIPT_DIR/config.sh" ]]; then
    echo "[ERROR] config.sh not found in $SCRIPT_DIR"
    echo "        Copy config.sh.example to config.sh and set your paths."
    exit 1
fi
source "$SCRIPT_DIR/config.sh"

RESULTS_DIR="$PROJECT_DIR/results"

# ─── CREATE RESULTS SUBDIRECTORIES ───────────────────────────────────────────
echo "[INFO] Creating output directories under: $RESULTS_DIR"

mkdir -p "$RESULTS_DIR"/{00_logs,01_annotation,02_mlst,03_ARG_RGI,\
04_ARG_amrfinder,05_VFG_abricate,06_plasmid_genomad,07_IS_isescan,\
08_prophage_genomad,09_SNP_phylogeny/{snippy_out,core_snps,iqtree},\
10_pangenome_roary,11_mob_suite,12_gtdbtk,13_summary_tables,\
14_abricate_resfinder,15_AbaRI_comM}

mkdir -p "$PROJECT_DIR/references"

echo "[INFO] Directories created."

# ─── VALIDATE ASSEMBLY DIRECTORY ─────────────────────────────────────────────
if [[ ! -d "$ASSEMBLY_DIR" ]]; then
    echo "[WARN] Assembly directory not found: $ASSEMBLY_DIR"
    echo "       Create it and place your .fna genome files there."
    mkdir -p "$ASSEMBLY_DIR"
fi

# ─── GENERATE SAMPLE LIST ────────────────────────────────────────────────────
SAMPLE_LIST="$PROJECT_DIR/samples.txt"
echo "[INFO] Generating sample list from: $ASSEMBLY_DIR"

ls "$ASSEMBLY_DIR"/*.fna 2>/dev/null \
    | xargs -I{} basename {} .fna \
    | grep -v '\.fai$' \
    | sort -u > "$SAMPLE_LIST" || true

TOTAL=$(wc -l < "$SAMPLE_LIST" || echo 0)
echo "[INFO] Found $TOTAL samples."
[[ "$TOTAL" -gt 0 ]] && cat "$SAMPLE_LIST"

# ─── WRITE METADATA TEMPLATE (fill in manually) ──────────────────────────────
META="$PROJECT_DIR/metadata.tsv"
if [[ ! -f "$META" ]]; then
    echo "[INFO] Writing metadata template: $META"
    cat > "$META" << 'EOF'
sample	collection_year	hospital	location	specimen	sequence_type
SAMPLE1	2020	Hospital_A	City_A	Blood	NA
SAMPLE2	2020	Hospital_B	City_B	Urine	NA
EOF
    echo "[INFO] Edit metadata.tsv to fill in your sample information."
fi

# ─── EXPORT ENVIRONMENT CONFIG ────────────────────────────────────────────────
ENV_CFG="$PROJECT_DIR/env_config.sh"
cat > "$ENV_CFG" << ENVEOF
# Auto-generated by step00_setup.sh — do NOT edit manually.
# Re-run step00_setup.sh after changing config.sh.
export PROJECT_DIR="$PROJECT_DIR"
export ASSEMBLY_DIR="$ASSEMBLY_DIR"
export RESULTS_DIR="$RESULTS_DIR"
export DB_BASE="$DB_BASE"
export SAMPLE_LIST="$PROJECT_DIR/samples.txt"
export METADATA="$PROJECT_DIR/metadata.tsv"
export REFERENCE_GENOME="$REFERENCE_GENOME"
export CARD_DB="$CARD_DB"
export VFDB="$VFDB"
export GENOMAD_DB="$GENOMAD_DB"
export MOB_DB="$MOB_DB"
export ABARI_DB="$ABARI_DB"
export GTDB_DATA="$GTDB_DATA"
export AMRFINDER_DB="$AMRFINDER_DB"
export THREADS="$THREADS"
ENVEOF

echo "[INFO] Environment config written to: $ENV_CFG"
echo ""
echo "=========================================="
echo "  SETUP COMPLETE — next: step01_annotation"
echo "  Total samples : $TOTAL"
echo "  Project dir   : $PROJECT_DIR"
echo "=========================================="
